const ProductList = [
  {
    ProductID: "1",
    ProductName: "Pentair Optiflo High Performance Pump",
    ProductUCost: "38,000",
    ProductImg: "prod_1",
    ProductCategory: "swimming-pool-pump",
  },
  {
    ProductID: "2",
    ProductName: "Pentair Whisperflo High Performance Pump AP011514",
    ProductUCost: "56,930",
    ProductImg: "prod_2",
    ProductCategory: "swimming-pool-pump",
  },
  {
    ProductID: "3",
    ProductName: "DICALITE Swimming Pool Filter Powder 22.7kg (USA)",
    ProductUCost: "3,333",
    ProductImg: "prod_3",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "4",
    ProductName:
      "Pentair Oto (orthotolidene) SWIMMING POOL Solution #1 R161004 (15 ml) - Solution #1",
    ProductUCost: "320",
    ProductImg: "prod_4",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "5",
    ProductName: "Hydro-Chlon 70% Granular For Swimming Pool (Japan)",
    ProductUCost: "13,500",
    ProductImg: "prod_5",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "6",
    ProductName: "Pentair Pool Test Kit and Solutions, #752 2 in 1 Test Kit",
    ProductUCost: "2,000",
    ProductImg: "prod_6",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "7",
    ProductName: "Zelbrite High Performance Pool Filter Media 15kg",
    ProductUCost: "1,880",
    ProductImg: "prod_7",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "8",
    ProductName: "Dry Acid For Swimming Pool",
    ProductUCost: "298",
    ProductImg: "prod_8",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "9",
    ProductName: "Aqua Chem D.E. Powder 20kg",
    ProductUCost: "2,350",
    ProductImg: "prod_9",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "10",
    ProductName: "Floating Dispenser Plus Neo-Chlor 90 Tablets Bundle",
    ProductUCost: "1,600",
    ProductImg: "prod_10",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "11",
    ProductName: "Sodium Bisulphate (Anhydrous, Technical Grade) 25kg",
    ProductUCost: "3,400",
    ProductImg: "prod_11",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "12",
    ProductName: "Sodium Bisulfate 25kg",
    ProductUCost: "3,400",
    ProductImg: "prod_12",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "13",
    ProductName: "Potassium Alum For Swimming Pool 1kg",
    ProductUCost: "498",
    ProductImg: "prod_13",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "14",
    ProductName: "Algaecide For Swimming Pool 1kg",
    ProductUCost: "480",
    ProductImg: "prod_14",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "15",
    ProductName: "Neo-Chlor 90% Chlorine Tablets Made In Japan 1kg",
    ProductUCost: "788",
    ProductImg: "prod_15",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "16",
    ProductName:
      "PENTAIR PHENOL RED SWIMMING POOL TEST KIT REAGENT R161018, (15 ml) - Solution #2",
    ProductUCost: "290",
    ProductImg: "prod_16",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "17",
    ProductName: "Granular 70% Japan Chlorine For Swimming Pool 1kg",
    ProductUCost: "298",
    ProductImg: "prod_17",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "18",
    ProductName: "90% Japan Chlorine For Swimming Pool 1kg",
    ProductUCost: "298",
    ProductImg: "prod_18",
    ProductCategory: "swimming-pool-chemical",
  },
  {
    ProductID: "19",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (1 piece small)",
    ProductUCost: "4,000",
    ProductImg: "prod_19",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "20",
    ProductName: "Pentair Pressure Gauge Top Mount Pentair Product No. 190058",
    ProductUCost: "1,250",
    ProductImg: "prod_20",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "21",
    ProductName: "Swimming Pool Filter O-Ring",
    ProductUCost: "2,710",
    ProductImg: "prod_21",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "22",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (1 piece large)",
    ProductUCost: "3,650",
    ProductImg: "prod_22",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "23",
    ProductName: "Pentair Clamp Band Replacement for DE Filter",
    ProductUCost: "5,850",
    ProductImg: "prod_23",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "24",
    ProductName: "Pentair Clamp Band Replacement For FNS Plus Filter",
    ProductUCost: "21,060",
    ProductImg: "prod_24",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "25",
    ProductName: "Pentair Cartridge Element For Easy Clean Filter EC90",
    ProductUCost: "18,700",
    ProductImg: "prod_25",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "26",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (set)",
    ProductUCost: "57,200",
    ProductImg: "prod_26",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "27",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (1 piece small)",
    ProductUCost: "4,930",
    ProductImg: "prod_27",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "28",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (1 piece small)",
    ProductUCost: "3,270",
    ProductImg: "prod_28",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "29",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (1 piece large)",
    ProductUCost: "3,190",
    ProductImg: "prod_29",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "30",
    ProductName: "Pentair Multi-Port Valve For Pool Filters Product # 261152",
    ProductUCost: "14,020",
    ProductImg: "prod_30",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "31",
    ProductName: "Pentair Basket Plastic Strainer For Pool Pump filter 355318",
    ProductUCost: "2,150",
    ProductImg: "prod_31",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "32",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (1 piece small)",
    ProductUCost: "2,890",
    ProductImg: "prod_32",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "33",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (1 piece large)",
    ProductUCost: "4,820",
    ProductImg: "prod_33",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "34",
    ProductName: "Pentair Cartridge Element For Easy Clean Filter EC60",
    ProductUCost: "11,640",
    ProductImg: "prod_34",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "35",
    ProductName: "Pentair EC 60 DE Element Filter Product No. 188614",
    ProductUCost: "32,470",
    ProductImg: "prod_35",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "36",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (set)",
    ProductUCost: "39,200",
    ProductImg: "prod_36",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "37",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (1 piece large)",
    ProductUCost: "5,480",
    ProductImg: "prod_37",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "38",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (set)",
    ProductUCost: "53,460",
    ProductImg: "prod_38",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "39",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (set)",
    ProductUCost: "43,790",
    ProductImg: "prod_39",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "40",
    ProductName:
      "Pentair High Flow Manual Air Relief Valve w/ Pressure Gauge For Pentair DE Filter 98209800",
    ProductUCost: "3,880",
    ProductImg: "prod_40",
    ProductCategory: "swimming-pool-filter",
  },
  {
    ProductID: "41",
    ProductName:
      "PENTAIR PHENOL RED SWIMMING POOL TEST KIT REAGENT R161018, (15 ml) - Solution #2",
    ProductUCost: "290",
    ProductImg: "prod_41",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "42",
    ProductName: "Floating Dispenser Plus Neo-Chlor 90 Tablets Bundle",
    ProductUCost: "1,600",
    ProductImg: "prod_42",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "43",
    ProductName:
      "Pentair Oto (orthotolidene) SWIMMING POOL Solution #1 R161004 (15 ml) - Solution #1",
    ProductUCost: "320",
    ProductImg: "prod_43",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "44",
    ProductName: "Pentair Pool Test Kit and Solutions, #752 2 in 1 Test Kit",
    ProductUCost: "2,000",
    ProductImg: "prod_44",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "45",
    ProductName: "Swimming Pool Leaf Scoop",
    ProductUCost: "850",
    ProductImg: "prod_45",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "46",
    ProductName: "Floating Dispenser For Chlorine Tablets",
    ProductUCost: "888",
    ProductImg: "prod_46",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "47",
    ProductName: "Vacuum Head Wheels 8 Pieces",
    ProductUCost: "860",
    ProductImg: "prod_47",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "48",
    ProductName: "Pentair Econo Triangular Vacuum Head Model #194",
    ProductUCost: "2,890",
    ProductImg: "prod_48",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "49",
    ProductName: "Pentair Leaf Scoop Aluminum Handle #119",
    ProductUCost: "1,330",
    ProductImg: "prod_49",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "50",
    ProductName: "Pentair Algae Brush Plastic Handle",
    ProductUCost: "1,100",
    ProductImg: "prod_50",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "51",
    ProductName: "Pentair Nylon Brush 18 inches Product No. APR111366",
    ProductUCost: "1,470",
    ProductImg: "prod_51",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "52",
    ProductName: 'Pool Vacuum Head with Brush 14""',
    ProductUCost: "888",
    ProductImg: "prod_52",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "53",
    ProductName: "Pool Vacuum Hose Highly Flexible 25 ft",
    ProductUCost: "2,800",
    ProductImg: "prod_53",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "54",
    ProductName: "Pool Vacuum Hose Highly Flexible 30 ft",
    ProductUCost: "3,300",
    ProductImg: "prod_53",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "55",
    ProductName: "Pool Vacuum Hose Highly Flexible 50 ft",
    ProductUCost: "5,100",
    ProductImg: "prod_53",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "56",
    ProductName: "Pool Vacuum Hose Highly Flexible 40 ft",
    ProductUCost: "4,200",
    ProductImg: "prod_53",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "57",
    ProductName: "Pool Vacuum Hose Highly Flexible 35 ft",
    ProductUCost: "3,800",
    ProductImg: "prod_53",
    ProductCategory: "swimming-pool-cleaning-tools",
  },
  {
    ProductID: "58",
    ProductName:
      "Pentair High Flow Manual Air Relief Valve w/ Pressure Gauge For Pentair DE Filter 98209800",
    ProductUCost: "3,880",
    ProductImg: "prod_40",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "59",
    ProductName: "Swimming Pool Filter O-Ring",
    ProductUCost: "2,710",
    ProductImg: "prod_21",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "60",
    ProductName: "Pentair Pressure Gauge Top Mount Pentair Product No. 190058",
    ProductUCost: "1,250",
    ProductImg: "prod_20",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "61",
    ProductName: "Pentair Multi-Port Valve For Pool Filters Product # 261152",
    ProductUCost: "14,020",
    ProductImg: "prod_30",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "62",
    ProductName: "Swimming Pool Return Fitting 3/4",
    ProductUCost: "330",
    ProductImg: "prod_54",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "63",
    ProductName: "Swimming Pool Skimmer (Small)",
    ProductUCost: "9,500",
    ProductImg: "prod_55",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "64",
    ProductName: "Hayward Jet Air Fitting For Jacuzzi SP1434",
    ProductUCost: "3,110",
    ProductImg: "prod_56",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "65",
    ProductName: "Swimming Pool Skimmer (Big)",
    ProductUCost: "10,500",
    ProductImg: "prod_57",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "66",
    ProductName: "Pentair 3-Way Valve PVC (2 inches)",
    ProductUCost: "2,170",
    ProductImg: "prod_58",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "67",
    ProductName: "Pentair Swimming Pool Deck Jet Assy II",
    ProductUCost: "4,500",
    ProductImg: "prod_59",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "68",
    ProductName: "Brass Fountain For Swimming Pool 3/4",
    ProductUCost: "800",
    ProductImg: "prod_60",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "69",
    ProductName: "Jacuzzi Switch Button",
    ProductUCost: "650",
    ProductImg: "prod_61",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "70",
    ProductName:
      "Swimming Pool Grating 9 inches (Anti-Slip Surface Swimming Pool Grill Drain Overflow Grating)",
    ProductUCost: "64",
    ProductImg: "prod_62",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "71",
    ProductName: "Pool Fountain Return Fitting",
    ProductUCost: "380",
    ProductImg: "prod_63",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "72",
    ProductName: "Brass Fountain For Swimming Pool 1/2",
    ProductUCost: "800",
    ProductImg: "prod_64",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "73",
    ProductName: "Swimming Pool Fountain Brass",
    ProductUCost: "3,500",
    ProductImg: "prod_65",
    ProductCategory: "swimming-pool-accessories",
  },
  {
    ProductID: "74",
    ProductName:
      "Pentair High Flow Manual Air Relief Valve w/ Pressure Gauge For Pentair DE Filter 98209800",
    ProductUCost: "3,880",
    ProductImg: "prod_40",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "75",
    ProductName: "Pentair Basket Plastic Strainer For Pool Pump filter 355318",
    ProductUCost: "2,150",
    ProductImg: "prod_31",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "76",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (1 piece small)",
    ProductUCost: "4,000",
    ProductImg: "prod_19",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "77",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (1 piece small)",
    ProductUCost: "2,890",
    ProductImg: "prod_32",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "78",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (1 piece large)",
    ProductUCost: "3,190",
    ProductImg: "prod_29",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "79",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (1 piece large)",
    ProductUCost: "3,650",
    ProductImg: "prod_22",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "80",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (1 piece small)",
    ProductUCost: "3,270",
    ProductImg: "prod_28",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "81",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (1 piece small)",
    ProductUCost: "4,930",
    ProductImg: "prod_27",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "82",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (1 piece large)",
    ProductUCost: "4,820",
    ProductImg: "prod_33",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "83",
    ProductName: "Vacuum Head Wheels 8 Pieces",
    ProductUCost: "860",
    ProductImg: "prod_47",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "84",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (1 piece large)",
    ProductUCost: "5,480",
    ProductImg: "prod_37",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "85",
    ProductName: "Swimming Pool Filter O-Ring",
    ProductUCost: "2,710",
    ProductImg: "prod_21",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "86",
    ProductName: "Pentair Econo Triangular Vacuum Head Model #194",
    ProductUCost: "2,890",
    ProductImg: "prod_48",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "87",
    ProductName: "Pentair Clamp Band Replacement for DE Filter",
    ProductUCost: "5,850",
    ProductImg: "prod_23",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "88",
    ProductName: "Pentair Pressure Gauge Top Mount Pentair Product No. 190058",
    ProductUCost: "1,250",
    ProductImg: "prod_20",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "89",
    ProductName: "Pentair DE Filter Element for FNS Plus 60 (set)",
    ProductUCost: "57,200",
    ProductImg: "prod_26",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "90",
    ProductName: "Pentair Cartridge Element For Easy Clean Filter EC90",
    ProductUCost: "18,700",
    ProductImg: "prod_25",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "91",
    ProductName: "Pentair Clamp Band Replacement For FNS Plus Filter",
    ProductUCost: "21,060",
    ProductImg: "prod_24",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "92",
    ProductName: "Pentair DE Filter Element for FNS Plus 24 (set)",
    ProductUCost: "39,200",
    ProductImg: "prod_36",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "93",
    ProductName: "Pentair DE Filter Element for FNS Plus 48 (set)",
    ProductUCost: "53,460",
    ProductImg: "prod_38",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "94",
    ProductName: "Pentair DE Filter Element for FNS Plus 36 (set)",
    ProductUCost: "43,790",
    ProductImg: "prod_39",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "95",
    ProductName: "Pentair Cartridge Element For Easy Clean Filter EC60",
    ProductUCost: "11,640",
    ProductImg: "prod_34",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "96",
    ProductName: "Swimming Pool Return Fitting 3/4",
    ProductUCost: "330",
    ProductImg: "prod_54",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "97",
    ProductName: 'Pool Vacuum Head with Brush 14""',
    ProductUCost: "888",
    ProductImg: "prod_52",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "98",
    ProductName: "Hayward Jet Air Fitting For Jacuzzi SP1434",
    ProductUCost: "3,110",
    ProductImg: "prod_56",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "99",
    ProductName: "Pentair Swimming Pool Deck Jet Assy II",
    ProductUCost: "4,500",
    ProductImg: "prod_59",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "100",
    ProductName:
      "Swimming Pool Grating 9 inches (Anti-Slip Surface Swimming Pool Grill Drain Overflow Grating)",
    ProductUCost: "64",
    ProductImg: "prod_62",
    ProductCategory: "swimming-pool-spare-parts",
  },
  {
    ProductID: "101",
    ProductName: "Swimming Pool Underwater LED Light",
    ProductUCost: "10,500",
    ProductImg: "prod_66",
    ProductCategory: "swimming-pool-underwater-lights",
  },
  {
    ProductID: "102",
    ProductName: "Pentair Globrite Underwater Light",
    ProductUCost: "23,320",
    ProductImg: "prod_67",
    ProductCategory: "swimming-pool-underwater-lights",
  },
  {
    ProductID: "103",
    ProductName: "Brass Fountain For Swimming Pool 3/4",
    ProductUCost: "800",
    ProductImg: "prod_60",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "104",
    ProductName: "Swimming Pool Fountain Brass",
    ProductUCost: "3,500",
    ProductImg: "prod_65",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "105",
    ProductName: "Brass Fountain For Swimming Pool 1/2",
    ProductUCost: "800",
    ProductImg: "prod_64",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "106",
    ProductName: "Hayward Jet Air Fitting For Jacuzzi SP1434",
    ProductUCost: "3,110",
    ProductImg: "prod_56",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "107",
    ProductName: "Pentair Swimming Pool Deck Jet Assy II",
    ProductUCost: "4,500",
    ProductImg: "prod_59",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "108",
    ProductName:
      "Swimming Pool Grating 9 inches (Anti-Slip Surface Swimming Pool Grill Drain Overflow Grating)",
    ProductUCost: "64",
    ProductImg: "prod_62",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "109",
    ProductName: "Jacuzzi Switch Button",
    ProductUCost: "650",
    ProductImg: "prod_61",
    ProductCategory: "other-swimming-pool-products",
  },
  {
    ProductID: "110",
    ProductName: "Safety Life Jacket For Adult",
    ProductUCost: "1,800",
    ProductImg: "prod_68",
    ProductCategory: "other-swimming-pool-products",
  },
];

export default ProductList;
